# Generated by Django 5.1.2 on 2024-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlindBoxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('contact', models.IntegerField(max_length=11, verbose_name='联系方式')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
                ('introduction', models.CharField(max_length=500, verbose_name='个人简介')),
                ('demand', models.CharField(max_length=500, verbose_name='需求')),
            ],
        ),
    ]
