# Generated by Django 5.1.2 on 2024-12-03 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindboxdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='blindboxdata',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='联系方式'),
        ),
    ]
