# Generated by Django 5.1.2 on 2024-12-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_blindboxdata_created_at_alter_blindboxdata_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindboxdata',
            name='email',
            field=models.EmailField(default='<EMAIL>', max_length=100, verbose_name='邮箱'),
        ),
    ]
