# Generated by Django 5.1.2 on 2024-12-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindboxdata',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
