# Generated by Django 5.1.2 on 2024-12-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_blindboxdata_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
