# Generated by Django 5.1.2 on 2024-12-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindboxdata',
            name='demand',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='blindboxdata',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介'),
        ),
    ]
