# Generated by Django 5.1.2 on 2024-12-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_blindboxdata_demand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindboxdata',
            name='demand',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='blindboxdata',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介'),
        ),
    ]
