# Generated by Django 5.1.2 on 2024-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
