# Generated by Django 5.1.2 on 2024-12-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_blindboxdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindboxdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.user', to_field='username', verbose_name='用户'),
        ),
    ]
