# Generated by Django 5.1.2 on 2024-12-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_blindboxdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='blind_box',
            field=models.ForeignKey(default=2361, on_delete=django.db.models.deletion.CASCADE, to='app01.blindboxdata', unique=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='blindboxdata',
            name='user',
            field=models.ForeignKey(default='夏冬俊', on_delete=django.db.models.deletion.CASCADE, to='app01.user', to_field='username', verbose_name='用户'),
        ),
    ]
