# Generated by Django 5.1.2 on 2024-12-17 07:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_yourmodel_comment_blind_box_alter_blindboxdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenMyself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
                ('introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('demand', models.CharField(blank=True, max_length=500, null=True, verbose_name='需求')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('user', models.ForeignKey(default='夏冬俊', on_delete=django.db.models.deletion.CASCADE, to='app01.user', to_field='username', verbose_name='用户')),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
