# Generated by Django 5.1.2 on 2024-12-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindboxComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='age',
            field=models.IntegerField(unique=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='contact',
            field=models.CharField(max_length=100, unique=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='demand',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='user',
            field=models.ForeignKey(default='夏冬俊', on_delete=django.db.models.deletion.CASCADE, to='app01.user', to_field='username', unique=True, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blind_box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.blindboxdata', unique=True, verbose_name='评论'),
        ),
    ]
