# Generated by Django 5.1.2 on 2024-12-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_blindboxcomment_alter_chosenmyself_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindboxdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='用户'),
        ),
    ]
