# Generated by Django 5.1.2 on 2024-12-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_blindboxdata_user_alter_chosenmyself_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindboxcomment',
            name='blind_box',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app01.blindboxdata', verbose_name='评论'),
        ),
    ]
