# Generated by Django 5.1.2 on 2024-12-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_blindboxcomment_blind_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='Tobbolc', on_delete=django.db.models.deletion.CASCADE, to='app01.user', to_field='username', verbose_name='用户'),
        ),
    ]
