# Generated by Django 5.1.2 on 2024-12-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_remove_comment_blind_box_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenmyself',
            name='address',
            field=models.CharField(max_length=100, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='demand',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='chosenmyself',
            name='user',
            field=models.ForeignKey(default='Tobbolc', on_delete=django.db.models.deletion.CASCADE, to='app01.user', to_field='username', verbose_name='用户'),
        ),
    ]
