# Generated by Django 5.1.2 on 2024-12-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_alter_chosenmyself_address_alter_chosenmyself_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenmyself',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
    ]
