# Generated by Django 5.1.2 on 2024-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_alter_chosenmyself_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
