# Generated by Django 5.1.2 on 2024-12-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
